import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const publicEnv = {
    "NEXT_PUBLIC_ENV": "public",
    "NEXT_PUBLIC_ENV_FROM_LAYOUT": "public-layout",
  };

  return (
    <html lang="en">
      <head>
        <Script 
            id="env-script"
            strategy="beforeInteractive">
          {`window['__ENV'] = ${JSON.stringify(publicEnv)}`}
        </Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
